openapi: 3.0.3
info:
  title: Infovis
  version: '1.0'
  x-logo:
    url: ''
paths:
# Agrupaciones --------------------------------------------------------------------------
  /agrupaciones:
    get:
      tags: 
        - agrupaciones
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/agrupacion'
# Cargos --------------------------------------------------------------------------
  /cargos:
    get:
      tags: 
        - cargos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/cargo'
          headers: {}
          links: {}
# PROVINCIAS --------------------------------------------------------------------------
  /provincias: 
    get:
      tags:
        - provincias
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/provincia'
  /provincias/{idProvincia}:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/provincia'
  /provincias/{idProvincia}/agrupaciones:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/agrupacion'

  /provincias/{idProvincia}/agrupaciones/{idAgrupacion}/cargos/{idCargo}/votos:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
        - $ref: '#/components/parameters/idAgrupacion'
        - $ref: '#/components/parameters/idCargo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: number

  /provincias/{idProvincia}/agrupaciones/votos:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/agrupacionCargoCantidad'
  
  /provincias/{idProvincia}/agrupaciones/{idAgrupacion}/votos:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
        - $ref: '#/components/parameters/idAgrupacion'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/cargoCantidad'

  /provincias/{idProvincia}/cargos:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/cargo'
  
  /provincias/{idProvincia}/tipovoto/{idTipoDeVoto}/votos:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
        - $ref: '#/components/parameters/idTipoDeVoto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/cargoCantidad'
# Tipo de votos --------------------------------------------------------------------------
  /tiposDeVotos:
    get:
      tags:
        - tipo de voto
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tipoDeVoto'
components:
  schemas:
    agrupacion:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
    agrupacionCargoCantidad:
      type: object
      properties:
        idAgrupacion:
          type: number
        idCargo:
          type: number
        cantidad:
          type: number
    cargo:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
    cargoCantidad:
      type: object
      properties:
        idCargo:
          type: number
        cantidad:
          type: number
    provincia:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
    tipoDeVoto:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
  headers: {}
  responses: {}
  parameters:
    idAgrupacion:
      name: idAgrupacion
      required: true
      in: path
      schema:
        type: number
    idCargo:
      name: idCargo
      required: true
      in: path
      schema:
        type: number
    idProvincia:
      name: idProvincia
      required: true
      in: path
      schema:
        type: number
    idTipoDeVoto:
      name: idTipoDeVoto
      required: true
      in: path
      schema:
        type: number

tags: []
servers:
  - url: ../api
    description: ''
    variables: {}