openapi: 3.0.3
info:
  title: Infovis
  version: '1.0'
  x-logo:
    url: ''
paths:
# Agrupaciones --------------------------------------------------------------------------
  /agrupaciones:
    get:
      tags: 
        - agrupaciones
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/agrupacion'
    
  /agrupaciones/{idAgrupacion}:
    get:
      tags: 
        - agrupaciones
      parameters:
        - $ref: '#/components/parameters/idAgrupacion'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/agrupacion'

# Cargos --------------------------------------------------------------------------
  /cargos:
    get:
      tags: 
        - cargos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/cargo'
          headers: {}
          links: {}

  /cargos/{idCargo}:
    get:
      tags: 
        - cargos
      parameters:
        - $ref: '#/components/parameters/idCargo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cargo'
          headers: {}
          links: {}
          

# Provincias --------------------------------------------------------------------------
  /provincias: 
    get:
      tags:
        - provincias
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/provincia'

  /provincias/{idProvincia}:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/provincia'

  /provincias/{idProvincia}/agrupaciones:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/agrupacionPorProv'

  /provincias/{idProvincia}/agrupaciones/{idAgrupacion}:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
        - $ref: '#/components/parameters/idAgrupacion'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/agrupacionPorProv'

  /provincias/{idProvincia}/cargos:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/cargoPorProv'

  /provincias/{idProvincia}/cargos/{idCargo}:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
        - $ref: '#/components/parameters/idCargo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cargoPorProv'

  /provincias/tipovoto:
    get:
      tags:
        - provincias
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tipovotoPorProv'
  
  /provincias/{idProvincia}/tipovoto:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tipovotoPorProvItem'
  
  /provincias/{idProvincia}/secciones:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/seccionesPorProv'

  /provincias/{idProvincia}/secciones/{idSeccion}:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
        - $ref: '#/components/parameters/idSeccion'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/seccionesPorProv'

  /provincias/{idProvincia}/cargos/{idCargo}/agrupaciones:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
        - $ref: '#/components/parameters/idCargo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/votosPorAgrupacion'

  /provincias/{idProvincia}/cargos/{idCargo}/agrupaciones/{idAgrupacion}:
    get:
      tags:
        - provincias
      parameters:
        - $ref: '#/components/parameters/idProvincia'
        - $ref: '#/components/parameters/idCargo'
        - $ref: '#/components/parameters/idAgrupacion'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/votosPorAgrupacion'

# Secciones --------------------------------------------------------------------------
  /secciones:
    get:
      tags:
        - secciones
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/secciones'

  /secciones/{idSecciones}:
    get:
      tags:
        - secciones
      parameters:
        - $ref: '#/components/parameters/idSeccion'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/secciones'
# Tipo de votos --------------------------------------------------------------------------
  /tiposDeVotos:
    get:
      tags:
        - tiposDeVotos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/tipoDeVoto'
  /tiposDeVotos/{idTipoDeVoto}:
    get:
      tags:
        - tiposDeVotos
      parameters:
        - $ref: '#/components/parameters/idTipoDeVoto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tipoDeVoto'

# Votos --------------------------------------------------------------------------
  /votos:
    get:
      tags:
        - votos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sum'


components:
  schemas:
    agrupacion:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
    agrupacionCargoCantidad:
      type: object
      properties:
        idAgrupacion:
          type: number
        idCargo:
          type: number
        cantidad:
          type: number
    cargo:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
    cargoCantidad:
      type: object
      properties:
        idCargo:
          type: number
        cantidad:
          type: number
    provincia:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
    secciones:
      type: object
      properties:
        id:
          type: number
        idProvincia:
          type: number
        name:
          type: string
    sum:
      type: number
    tipoDeVoto:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
    agrupacionPorProv:
      type: object
      properties:
        idprovincia: 
          type: number
        provincia:  
          type: string
        idagrupacion:  
          type: number
        agrupacion:  
          type: string

    cargoPorProv:
      type: object
      properties:
        idprovincia: 
          type: number
        provincia:  
          type: string
        idcargo:  
          type: number
        cargo:  
          type: string

    tipovotoPorProv:
      type: object
      additionalProperties:
        type: array
        items:
          type: array
          items:
            $ref: '#/components/schemas/tipovotoPorProvItem'
    tipovotoPorProvItem:
      type: object
      properties:
        idtipovotos:
          type: number
        votos:
          type: number  
    seccionesPorProv:
      type: object
      properties:
        idProvincia:
          type: number
        idSeccion:
          type: number  
    votosPorAgrupacion:
      type: object
      properties:
        idAgrupacion:
          type: number
        votos:
          type: number  

  headers: {}
  responses: {}
  parameters:
    idAgrupacion:
      name: idAgrupacion
      required: true
      in: path
      schema:
        type: number
    idCargo:
      name: idCargo
      required: true
      in: path
      schema:
        type: number
    idProvincia:
      name: idProvincia
      required: true
      in: path
      schema:
        type: number
    idSeccion:
      name: idSeccion
      required: true
      in: path
      schema:
        type: number
    idTipoDeVoto:
      name: idTipoDeVoto
      required: true
      in: path
      schema:
        type: number

tags: []
servers:
  - url: ../api
    description: ''
    variables: {}